inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - Guardfile
    - db/**
    - vendor/**/* # CI

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: [describe, context, feature]

Style/RegexpLiteral:
  AllowInnerSlashes: true
