AllCops:
  Excludes:
    - test/**
    - db/**
    - config/**/*
    - script/**
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 40
Metrics/BlockLength:
  Max: 80
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Max: 50
