sudo: required
dist: trusty
notifications:
  email: false
install:
# Run it once if main Dockerfile is changed
- docker build -t parsers .
- docker save parsers | gzip > docker/parsers.tar.gz
cache:
  bundler: true
  directories:
  - docker
language: ruby
rvm:
  - 2.5.1
env:
  global:
  - CC_TEST_REPORTER_ID=73d49b65ef405450e8f6d2b9c4a8030259dc91d1e8bf31f195765ace498d80d6
services:
  - docker
before_script:
  - gem update --system
  - gem install bundler:1.17.2
  - bundle install

  # Install dependencies.
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get install --reinstall dpkg
  - sudo apt-get install -y openjdk-8-jre-headless xvfb libxi6 libgconf-2-4

  # Install Chrome.
  - wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -P ~/
  - sudo dpkg -i --force-depends ~/google-chrome-stable_current_amd64.deb
  - sudo apt-get -f install -y
  - sudo dpkg -i --force-depends ~/google-chrome-stable_current_amd64.deb

  # Install ChromeDriver.
  - wget -N http://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

  # Install Selenium.
  - wget -N http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar -P ~/
  - sudo mv -f ~/selenium-server-standalone-3.4.0.jar /usr/local/share/
  - sudo chmod +x /usr/local/share/selenium-server-standalone-3.4.0.jar
  - sudo ln -s /usr/local/share/selenium-server-standalone-3.4.0.jar /usr/local/bin/selenium-server-standalone-3.4.0.jar

  # Codeclimate coverage reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

  # Docker cache
  - gzip -dc docker/parsers.tar.gz | docker load
script:
  - ENV=test bundle exec rspec
  - docker build -f Dockerfile.dev -t parsers_dev .
  - docker run -it --rm --env BROWSER='chrome' -v `pwd`:/parsers parsers_dev /bin/sh -c "rbenv exec bundle exec rspec"
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
