version: "1.{build}"

environment:
  matrix:
    - RUBY_VERSION: 25-x64
install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - git clone https://github.com/codahale/bcrypt-ruby.git
  - cd bcrypt-ruby
  - gem build bcrypt.gemspec
  - gem install gem-compiler
  - gem compile bcrypt-3.1.11.gem
  - gem install ./bcrypt-3.1.11-x64-mingw32.gem
  - cd ..
  - gem update --system
  - gem update bundler
  - bundle install
build: off
services: postgresql
test_script:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - set ENV=test
  - bundle exec rspec
